
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - custom.instana.io
  resources:
  - dashboards
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - custom.instana.io
  resources:
  - dashboards/finalizers
  verbs:
  - update
- apiGroups:
  - custom.instana.io
  resources:
  - dashboards/status
  verbs:
  - get
  - patch
  - update
